export const data = [
    {
        campaign_title: 'Save the Florida Bonneted Bat',
        description: 'saving the endangered bonneted bat',
        species: 'bat',
        location: 'Southern Florida',
        urgency: 'medium',
        donation_goal: 10000,
        organization_id: 1,
    },
    {
        campaign_title: 'Save the Florida Bonneted Bat',
        description: 'saving the endangered bonneted bat',
        species: 'bat',
        location: 'Southern Florida',
        urgency: 'medium',
        donation_goal: 10000,
        organization_id: 2,
    },
    {
        campaign_title: 'Save the Florida Bonneted Bat',
        description: 'saving the endangered bonneted bat',
        species: 'bat',
        location: 'Southern Florida',
        urgency: 'medium',
        donation_goal: 10000,
        organization_id: 3,
    },
    {
        campaign_title: 'Save the Florida Bonneted Bat',
        description: 'saving the endangered bonneted bat',
        species: 'bat',
        location: 'Southern Florida',
        urgency: 'medium',
        donation_goal: 10000,
        organization_id: 4,
    },
    {
        campaign_title: 'Save the Florida Bonneted Bat',
        description: 'saving the endangered bonneted bat',
        species: 'bat',
        location: 'Southern Florida',
        urgency: 'medium',
        donation_goal: 10000,
        organization_id: 5,
    },
    {
        campaign_title: 'Save the Florida Bonneted Bat',
        description: 'saving the endangered bonneted bat',
        species: 'bat',
        location: 'Southern Florida',
        urgency: 'medium',
        donation_goal: 10000,
        organization_id: 6,
    },
    {
        campaign_title: 'Save the Florida Bonneted Bat',
        description: 'saving the endangered bonneted bat',
        species: 'bat',
        location: 'Southern Florida',
        urgency: 'medium',
        donation_goal: 10000,
        organization_id: 7,
    },
    {
        campaign_title: 'Save the Florida Bonneted Bat',
        description: 'saving the endangered bonneted bat',
        species: 'bat',
        location: 'Southern Florida',
        urgency: 'medium',
        donation_goal: 10000,
        organization_id: 8,
    },
    {
        campaign_title: 'Save the Florida Bonneted Bat',
        description: 'saving the endangered bonneted bat',
        species: 'bat',
        location: 'Southern Florida',
        urgency: 'medium',
        donation_goal: 10000,
        organization_id: 9,
    },
    {
        campaign_title: 'Save the Florida Bonneted Bat',
        description: 'saving the endangered bonneted bat',
        species: 'bat',
        location: 'Southern Florida',
        urgency: 'medium',
        donation_goal: 10000,
        organization_id: 10,
    },

]